### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by kewp** [monty5811/postcss-elm-tailwind#33]
Not sure what I'm doing wrong. Can't find the module anywhere in `elm.json`....

```
-- MODULE NOT FOUND -- C:\Users\karlp\tst\postcss-elm-tailwind\demo\src\Main.elm

You are trying to import a `TLWND` module:

7| import TLWND as TW
          ^^^^^
I checked the "dependencies" and "source-directories" listed in your elm.json,
but I cannot find it! Maybe it is a typo for one of these names?
```

**Comment by sparksp** [comment]
Thanks for your report - can you share the steps you've used? Have you run `postcss` after configuring the plugin?

**Comment by kewp** [comment]
Not sure how you mean 'configuring the plugin'? I'm an Elm beginner I'm afraid...

This is what happens when I run `npm run build` (and I have run `npm install`...)

```c:\Users\karl\tst\postcss-elm-tailwind\demo>npm run build

> postcss-elm-tailwind-demo@1.0.0 build c:\Users\karl\tst\postcss-elm-tailwind\demo
> yarn build-tw && yarn build-elm && yarn copy-index

yarn run v1.22.4
$ postcss -o dist/main.css main.css
Error: Cannot find module 'postcss'
Require stack:
- c:\users\karlp\tst\postcss-elm-tailwind\index.js
- c:\users\karlp\tst\postcss-elm-tailwind\demo\postcss.config.js
- c:\users\karlp\tst\postcss-elm-tailwind\demo\node_modules\import-fresh\index.js
- c:\users\karlp\tst\postcss-elm-tailwind\demo\node_modules\cosmiconfig\dist\loaders.js
- c:\users\karlp\tst\postcss-elm-tailwind\demo\node_modules\cosmiconfig\dist\createExplorer.js
- c:\users\karlp\tst\postcss-elm-tailwind\demo\node_modules\cosmiconfig\dist\index.js
- c:\users\karlp\tst\postcss-elm-tailwind\demo\node_modules\postcss-load-config\src\index.js
- c:\users\karlp\tst\postcss-elm-tailwind\demo\node_modules\postcss-cli\index.js
- c:\users\karlp\tst\postcss-elm-tailwind\demo\node_modules\postcss-cli\bin\postcss
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (c:\users\karlp\tst\postcss-elm-tailwind\index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\users\\karlp\\tst\\postcss-elm-tailwind\\index.js',
    'c:\\users\\karlp\\tst\\postcss-elm-tailwind\\demo\\postcss.config.js',
    'c:\\users\\karlp\\tst\\postcss-elm-tailwind\\demo\\node_modules\\import-fresh\\index.js',
    'c:\\users\\karlp\\tst\\postcss-elm-tailwind\\demo\\node_modules\\cosmiconfig\\dist\\loaders.js',
    'c:\\users\\karlp\\tst\\postcss-elm-tailwind\\demo\\node_modules\\cosmiconfig\\dist\\createExplorer.js',
    'c:\\users\\karlp\\tst\\postcss-elm-tailwind\\demo\\node_modules\\cosmiconfig\\dist\\index.js',
    'c:\\users\\karlp\\tst\\postcss-elm-tailwind\\demo\\node_modules\\postcss-load-config\\src\\index.js',
    'c:\\users\\karlp\\tst\\postcss-elm-tailwind\\demo\\node_modules\\postcss-cli\\index.js',
    'c:\\users\\karlp\\tst\\postcss-elm-tailwind\\demo\\node_modules\\postcss-cli\\bin\\postcss'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! postcss-elm-tailwind-demo@1.0.0 build: `yarn build-tw && yarn build-elm && yarn copy-index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the postcss-elm-tailwind-demo@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\karlp\AppData\Roaming\npm-cache\_logs\2020-11-03T09_06_31_798Z-debug.log
```

**Comment by sparksp** [comment]
Ah, that's an issue specifically with the demo. You just need to run `npm install` in the `postcss-elm-tailwind` directory, before trying to build the demo. This is because the demo uses the local copy of postcss-elm-tailwind directly.

**Comment by kewp** [comment]
Oh I see. But how does the demo find the import for `TLWND`?

Hmmm does seem to be working...

**Comment by kewp** [comment]
Oh I see. So you generate the .elm files using Javascript...

**Comment by sparksp** [comment]
Yes, that's exactly it. Once the Tailwind CSS is generated the plugin then finds all the class names and generates an Elm module for them. Then it's based on your tailwind config and only gives you class names valid for your setup.

**Comment by kewp** [comment]
I see. Ok cool, thanks for helping me with this :). Going to close the issue then.
